language: objective-c
osx_image: beta-xcode6.3

cache:
  - bundler
  - cocoapods

before_install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet

script:
  - xcodebuild -project Sweet/Sweet.xcodeproj -scheme SweetTests -destination 'platform=iOS Simulator,name=iPhone Retina (4-inch),OS=8.1' build test | xcpretty -c; exit ${PIPESTATUS[0]}
