language: objective-c
osx_image: beta-xcode6.3

cache:
  - bundler
  - cocoapods

before_install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet

script:
  - xcodebuild -project Sweet/Sweet.xcodeproj -scheme SweetTests -sdk iphonesimulator8.3 build test | xcpretty -c; exit ${PIPESTATUS[0]}
