language: objective-c
osx_image: beta-xcode6.3

before_install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet

script:
- xcodebuild -project Sweet/Sweet.xcodeproj -scheme SweetTests build test | xcpretty -c; exit ${PIPESTATUS[0]}
